#!/bin/bash
local-update(){
	apt-get update && apt-get dist-upgrade -y
}
local-install(){
	apt-get install "$@"
}
local-search(){
	apt-cache search "$@"
}
local-detail(){
	apt-cache show "$@"
	apt-cache show-pkg "$@"
}
