#!/usr/bin/env bash
#packages needed: libtool pkg-config build-essential
PREFIX=$( pwd )/prefix
SSLDIR=$PREFIX/lib/ssl
export ACLOCAL_PATH=$PREFIX/share/aclocal
export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
MODE=static
unset LANG
set -e

compile-gen(){
	if [[ -n "$2" ]] ; then
		 "$2"
	fi
	./configure $1 --prefix=$PREFIX
	make install
}
build-gen(){
	cd "$1"
	"${@:2}"
	cd ..
}
build-gen-d(){ build-gen "$1" compile-gen "${@:2}" ; }
dep-build-gen(){
	for dir in "$@" ; do
		build-$dir-$MODE
	done
}
dep-build-libtorrent-gen(){ 
	dep-build-gen zlib openssl cppunit curl libtorrent
}
dep-build-rtorrent-gen(){ 
	dep-build-libtorrent-gen
	dep-build-gen ncurses rtorrent
}

compile-rtorrent-gen(){
	export LDFLAGS="-L/hax/ard/prefix/lib -lncurses"
	export CFLAGS="-I/hax/ard/prefix/include/ncurses -I/hax/ard/prefix/include"
	export CPPFLAGS="$CFLAGS"
	export LIBS=-ldl
	./autogen.sh
	./configure "$@" --prefix=$PREFIX
	make install
}
compile-openssl-gen(){
	export CFLAGS="-fPIC" 
	./Configure "$@" -fPIC -DOPENSSL_PIC --prefix=$PREFIX --openssldir=$SSLDIR --with-zlib-include=$PREFIX/include --with-zlib-lib=$PREFIX/lib linux-x86_64
	make install
}
ATSH="--disable-static --enable-shared"
ATST="--enable-static --disable-shared"
build-openssl-shared(){ build-gen openssl compile-openssl-gen shared zlib-dynamic ; }
build-openssl-static(){ build-gen openssl compile-openssl-gen no-shared zlib ; }
build-rtorrent-shared(){ build-gen rtorrent compile-rtorrent-gen $ATSH ; }
build-rtorrent-static(){ build-gen rtorrent compile-rtorrent-gen $ATST ; }
build-zlib-shared(){ build-gen-d zlib ; }
build-zlib-static(){ build-gen-d zlib --static ; }
build-libtorrent-shared(){ build-gen-d libtorrent "$ATSH --with-posix-fallocate --with-zlib=$PREFIX" "./autogen.sh" ; }
build-libtorrent-static(){ build-gen-d libtorrent "$ATST --with-posix-fallocate --with-zlib=$PREFIX" "./autogen.sh" ; }
build-ncurses-shared(){ build-gen-d ncurses "--with-shared --without-normal --without-debug --with-widec --enable-pc-files --with-pkg-config" ; }
build-ncurses-static(){ build-gen-d ncurses "--without-shared --with-normal --without-debug --with-widec --enable-pc-files --with-pkg-config" ; }
build-cppunit-shared(){ build-gen-d cppunit "$ATSH" "./autogen.sh" ; }
build-cppunit-static(){ build-gen-d cppunit "$ATST" "./autogen.sh" ; }
build-curl-shared(){ build-gen-d curl "$ATSH --with-ssl=$SSLDIR --with-zlib" "./buildconf" ; }
build-curl-static(){ build-gen-d curl "$ATST --with-ssl=$SSLDIR --with-zlib" "./buildconf" ; }

if [[ -n "$2" ]] ; then
	$2-build-$1-$MODE
elif [[ -n "$1" ]] ; then
	build-$1-$MODE
else
	dep-build-rtorrent-$MODE
fi
