#!/bin/bash
linuxcoded=/usr/local/src/linux-3.1x/linux-next/
linuxconf=nconfig
linux-localversion(){
	grep LOCALVERSION= .config | cut -d'"' -f2
}
linux-iterate(){
	set -e
	cd $linuxcoded
	make $linuxconf
	if [[ $! -ne 0 ]] ; then
		exit 255
	fi
	pause
	cp .config .config.`epoch`
	make deb-pkg -j3
	cd ..
	dpkg -i *.deb
	rm *.deb
	set +e
}
linux(){
	in="$1"
	shift
	echo linux\ 
	case "$in" in
		i)	linux-iterate "$@"
	esac
}

