#!/system/xbin/bash
sshdport=23
proxy=user@ennorath.ca
xenv=/system/xbin/env
xchroot=/system/xbin/chroot
xsshd=/system/bin/sshd
xssh=/system/bin/ssh
xmount=/system/bin/mount
pthis="$( cd "$( echo "${BASH_SOURCE[0]%/*}" )" && pwd )"
fthis=$0
xthis=$pthis/$fthis
pchroot=/mnt/deb-armel
xcbash=/bin/bash
start-sshd(){
	$xsshd -de -p $sshdport 
}
start-tunnel(){
	$xssh -fNR 0:localhost:$sshdport $proxy >& link
}
bind-mount(){
	$xmount -o bind $1 $2/$1
}
ensure-mount(){
	if ( $xmount | grep -q $2/$1 ) ; then
		echo "$1 already mounted."
	else
		bind-mount $1 $2
	fi
}
enter-chroot-noenv(){
	ensure-mount /dev $pchroot
	cp $xthis $pchroot/$fthis
	$xenv - $xchroot $pchroot $xcbash /$fthis prepare-chroot-env
	umount $pchroot/dev
}
prepare-chroot-env(){
	export TERM=xterm
	export PATH=$PATH
	export HOME=/root
	mount -t proc none /proc
	mount -t sysfs none /sys
	mount -t devpts none /dev/pts
	bash -l
	umount /proc
	umount /sys
	umount /dev/pts
}
show-path(){
	echo "$fthis"
	echo "$pthis"
	echo "$xthis"
}
#set -x
$@ 

