#!/bin/bash
nope(){
	if "${@:2}" ; then echo nope $1 ; exit $1 ; fi
}
nope 1 [ -z "$1" ] 
clean(){
	nope 2 [ $( head -c1 <<<"$1" ) == / ] 
	rm -rf $1/var/cache/apt/*
	rm -rf $1/var/lib/apt/lists/*
}
archive(){
	clean $1
	cd $1
	local fn=$1-$2.tar
	tar cf ../$fn *
	cd ..
	lrzip -o $fn.larz $fn & 
}
enter(){
	systemd-nspawn -bD $1 "${@:2}"
}
within(){
	systemd-nspawn -D $1 "${@:2}"
}
refresh(){
	within $1 apt-get update
}
indir(){
	cd $1
	eval "${@:2}"
	cd ..
}
collect(){
	indir $1 tar cf ../$1.collection \*
}
pack(){
	collect unstable
	( time ( lrzip -fvvo $1.pack $1.collection |& tr '\r' '\n' >> util.log ) &>> util.log ) &
}
save(){
	pack $1
	mv $1.pack states/$1-$2.larz
	rm $1.collection
}
"$@"
